/*
#ifndef FOG_MOD_NVG_CONSTANTS
#define FOG_MOD_NVG_CONSTANTS

const int FOG_NVTYPE_DUAL = 742101;
const int FOG_NVTYPE_GPNVG = 742102;

const int FOG_EFFECT_NVG_DUAL_OCCLUDER = 742001;
const int FOG_EFFECT_NVG_GPNVG_OCCLUDER = 742002;

const int FOG_NV_CLEAN_GREEN = 1000;

#endif
*/
